"use client"

import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import SideBar from "./sideBar";
import NavBar from './navBar';
import { Drawer } from '@mui/material';
import { useState } from 'react';


const inter = Inter({ subsets: ["latin"] }); 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const toggleDrawer =
    ( open: boolean) =>
   
    (event: React.KeyboardEvent | React.MouseEvent) => {

      console.log('etrweretruwet')
      if (
        event.type === 'keydown' &&
        ((event as React.KeyboardEvent).key === 'Tab' ||
          (event as React.KeyboardEvent).key === 'Shift')
      ) {
        return;
      }

      setDrawerOpen(open);
    };

    const handleToggleClick = () =>{
      console.log('set drawer open');
      setDrawerOpen(true);
    }

  return (
    <html lang="en">
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <body  className={inter.className}>
          <main className={styles.layoutWrapper}>
            <Drawer
              anchor={'left'}
              open={drawerOpen}
              onClose={toggleDrawer( false)}
              sx ={{width: '20px'}}
            >
              <SideBar className={styles.displaySide1} />
            </Drawer>
            <SideBar className={styles.displaySide2}/>
            <div className={styles.contentWrapper}>
              <NavBar handlclick={handleToggleClick}/>
              <div className={styles.content}>
                {children}
              </div>
            </div>
          </main>
        </body>
      </LocalizationProvider>
    </html>
  );
}
