"use client"
import Image from "next/image";

//import type { Metadata } from "next";
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import NavItem from "./navItem";

const inter = Inter({ subsets: ["latin"] }); 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navItems = [
  {
    name: 'Dashboard',
    svg: 'dashboard.svg'
  },
  {
    name: 'Courses',
    svg: 'courses.svg'
  },
  {
    name: 'Result Checking',
    svg: 'result.svg'
  },
  {
    name: 'Transcripts',
    svg: 'transcript.svg'
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <body  className={inter.className}>
          <main className={styles.layoutWrapper}>
            <div className={styles.sidebarWrapper}>
              <aside className={styles.sidebar}>
                <div>
                  <div></div>
                  <h2>Federal University of Technology, Akure</h2>
                </div>
                <div>
                  {
                    navItems.map((item, index) => <NavItem  svg={item.svg} name={item.name}/>)
                  }
                </div>
                <div>
                  <p>This solution is designed and delivered by <b>NEDSIS</b></p>
                  <Image
                      src="/nedsisLogo.svg"
                      alt="Search Logo"
                      width={100}
                      height={50}
                    />
                </div>
              </aside>
            </div>
            <div className={styles.contentWrapper}>
              <div className={styles.navbar}>
                <h4>Hi Student name</h4>
                <div>
                  <div>
                    <input placeholder="search"/>
                    <Image
                      src="/search.svg"
                      alt="Search Logo"
                      width={24}
                      height={24}
                      priority
                    />
                  </div>
                </div>
                <div>
                  <div>
                    <Image
                      src="/help.svg"
                      alt="Search Logo"
                      width={24}
                      height={24}
                      priority
                    />
                    <span>Help</span>
                  </div>
                  <div>
                    <Image
                      src="/logout.svg"
                      alt="Search Logo"
                      width={24}
                      height={24}
                      priority
                    />
                    <span>Logout</span>
                  </div>

                </div>
              </div>
              <div className={styles.content}>
                {children}
              </div>
            </div>
          </main>
        
        </body>
      </LocalizationProvider>
    </html>
  );
}
